### PR TITLE
chore(gatsby): product content resolvers

### PR DESCRIPTION
**Pull request by alexcasche**
### WHY are these changes introduced?

Addresses 
 - [ENG-5731](https://nacelle.atlassian.net/browse/ENG-5731)

### WHAT is this pull request doing?

- Removes secondary fetch to resolve referenced products `utils/resolvers`
- Refactors `gatsby-config.js` to import `createPages` and `createResolvers`
- Uses `createResolvers` to allow for querying referenced products in initial queries.

## 

### Testing
- `git checkout ENG-5731/gatsby-product-content-resolvers`
- `cd references-stores/gatsby`
- delete `node_modules/@nacelle/gatsby-source-nacelle`
- `npm install`
- `npm run clean && npm run develop`
- See products displayed in `FeaturedProducts` section on homepage, and  in `CartCrosssells` component in cart

### CODE REVIEW

**Comment by mdarrik** [comment]
This might be a local sharp thing.. But I get this issue when trying to run `npm run develop`


```
warn You can't use childImageSharp together with Smiles_Sunshine_3.gif — use publicURL instead. The childImageSharp portion of the query in this file will return null:
undefined
⠧ createPages
[============================]   1.521 s 219/219 100% Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs
/Users/darrik/github/getnacelle/nacelle-js/reference-stores/gatsby/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: Cannot read properties of undefined (reading 'bitmap')
    at Potrace._processLoadedImage (/Users/darrik/github/getnacelle/nacelle-js/reference-stores/gatsby/node_modules/@gatsbyjs/potrace/lib/Potrace.js:1002:35)
    at Jimp.<anonymous> (/Users/darrik/github/getnacelle/nacelle-js/reference-stores/gatsby/node_modules/@gatsbyjs/potrace/lib/Potrace.js:1048:14)
    at Timeout._onTimeout (/Users/darrik/github/getnacelle/nacelle-js/reference-stores/gatsby/node_modules/@jimp/core/src/index.js:223:9)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7)
```

**Comment by alexcasche** [comment]
> This might be a local sharp thing.. But I get this issue when trying to run `npm run develop`
> 
> ```
> warn You can't use childImageSharp together with Smiles_Sunshine_3.gif — use publicURL instead. The childImageSharp portion of the query in this file will return null:
> undefined
> ⠧ createPages
> [============================]   1.521 s 219/219 100% Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs
> /Users/darrik/github/getnacelle/nacelle-js/reference-stores/gatsby/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
>         throw ex;
>         ^
> 
> TypeError: Cannot read properties of undefined (reading 'bitmap')
>     at Potrace._processLoadedImage (/Users/darrik/github/getnacelle/nacelle-js/reference-stores/gatsby/node_modules/@gatsbyjs/potrace/lib/Potrace.js:1002:35)
>     at Jimp.<anonymous> (/Users/darrik/github/getnacelle/nacelle-js/reference-stores/gatsby/node_modules/@gatsbyjs/potrace/lib/Potrace.js:1048:14)
>     at Timeout._onTimeout (/Users/darrik/github/getnacelle/nacelle-js/reference-stores/gatsby/node_modules/@jimp/core/src/index.js:223:9)
>     at listOnTimeout (node:internal/timers:557:17)
>     at processTimers (node:internal/timers:500:7)
> ```

I was getting that same warning.  To bo honest I have no idea what that image even is.  Open to ideas.

**Comment by mdarrik** [comment]
Yeah, unsure of where the warning is coming from. Looks to be one of the products... 

But the error that was getting thrown is because of an issue with TRACED_SVG. I've not been able to use it on my local machine for a while now. Most people experiencing this issue have dropped it -> https://github.com/gatsbyjs/gatsby/issues/12552 


If it works for you and works for Vercel, then id doesn't _really_ matter. But if anyone else has issues with the build, replacing all TRACED_SVG with BLURRED allows the site to build for me

**Comment by mdarrik** [comment]
Also, the site doesn't seem to have a home page? (Only calling it out because it's one of the testing steps in the PR description)


home page of site with warning from Gatsby that the site doesn't have a home page and instructions on how to make one

**Comment by alexcasche** [comment]
> Also, the site doesn't seem to have a home page? (Only calling it out because it's one of the testing steps in the PR description)
> 
> home page of site with warning from Gatsby that the site doesn&apos;t have a home page and instructions on how to make one

Have you deleted `node_modules` and re-installed within `reference-stores/gatsby`.  I'm seeing all the pages load as expected.  If it's still broken I can slack you my `env`

**Comment by mdarrik** [comment]
Yeah. I realized it's because of this GQL error that I'm getting: 

```
GraphQLError: Unknown type "NacelleContentRemoteSectionSideBySide". Did you mean "NacelleContentRemoteSectionSideBySideFull", "NacelleContentRemoteSectionHeroEdge", "NacelleCont
  entRemoteSectionSideBySideFullEdge", "NacelleContentRemoteSectionTeamBios", or "NacelleContentRemoteSectionTeamBiosEdge
```

**Comment by alexcasche** [comment]
> Yeah. I realized it's because of this GQL error that I'm getting:
> 
> ```
> GraphQLError: Unknown type "NacelleContentRemoteSectionSideBySide". Did you mean "NacelleContentRemoteSectionSideBySideFull", "NacelleContentRemoteSectionHeroEdge", "NacelleCont
>   entRemoteSectionSideBySideFullEdge", "NacelleContentRemoteSectionTeamBios", or "NacelleContentRemoteSectionTeamBiosEdge
> ```

Likely related to the image stuff.  How do you feel about removing `TRACED_SVG`.  I assume that might be causing all sorts of issues on your end

**Comment by mdarrik** [comment]
> > Yeah. I realized it's because of this GQL error that I'm getting:
> > ```
> > GraphQLError: Unknown type "NacelleContentRemoteSectionSideBySide". Did you mean "NacelleContentRemoteSectionSideBySideFull", "NacelleContentRemoteSectionHeroEdge", "NacelleCont
> >   entRemoteSectionSideBySideFullEdge", "NacelleContentRemoteSectionTeamBios", or "NacelleContentRemoteSectionTeamBiosEdge
> > ```
> 
> Likely related to the image stuff. How do you feel about removing `TRACED_SVG`. I assume that might be causing all sorts of issues on your end

I did that already. This is a new error. It's saying that `NacelleContentRemoteSectionSideBySide` doesn't exist, but it's being queried for. (If I run develop, only `NacelleContentRemoteSectionSideBySideFull` seems to exist for sideBySide types)

**Comment by alexcasche** [comment]
> > > Yeah. I realized it's because of this GQL error that I'm getting:
> > > ```
> > > GraphQLError: Unknown type "NacelleContentRemoteSectionSideBySide". Did you mean "NacelleContentRemoteSectionSideBySideFull", "NacelleContentRemoteSectionHeroEdge", "NacelleCont
> > >   entRemoteSectionSideBySideFullEdge", "NacelleContentRemoteSectionTeamBios", or "NacelleContentRemoteSectionTeamBiosEdge
> > > ```
> > 
> > 
> > Likely related to the image stuff. How do you feel about removing `TRACED_SVG`. I assume that might be causing all sorts of issues on your end
> 
> I did that already. This is a new error. It's saying that `NacelleContentRemoteSectionSideBySide` doesn't exist, but it's being queried for. (If I run develop, only `NacelleContentRemoteSectionSideBySideFull` seems to exist for sideBySide types)

Are you running `npm run clean` first?

**Comment by mdarrik** [comment]
Yep. Each time

**Comment by alexcasche** [comment]
> Yep. Each time

@jasonredick @NWRichmond @KrisQ could one of you try this branch?  Curious to see if the issue is isolated to Darrik's machine.

**Comment by KrisQ** [comment]
> > Yep. Each time
> 
> @jasonredick @NWRichmond @KrisQ could one of you try this branch? Curious to see if the issue is isolated to Darrik's machine.

Seems to work well on my machine:


Screen Shot 2022-06-07 at 2 37 42 PM

**Comment by alexcasche** [comment]
> > > Yep. Each time
> > 
> > 
> > @jasonredick @NWRichmond @KrisQ could one of you try this branch? Curious to see if the issue is isolated to Darrik's machine.
> 
> Seems to work well on my machine as well:
> 
> Screen Shot 2022-06-07 at 2 37 42 PM

Yup it was an `env` issue

**Review by KrisQ — APPROVED** [review]
Looks good!

**Review by mdarrik — APPROVED** [review]
After resolving the env issue, is working as expected! LGTM!

**Pull request merged**
