### PR TITLE
chore: remove `complexity error` error handling

### PR DESCRIPTION
**Pull request by KrisQ**
## Why are these changes introduced?

Addresses [ENG-8823](https://nacelle.atlassian.net/browse/ENG-8823) 

## What is this pull request doing?

- Update the Commerce Queries plugin to just throw the error.message instead of handling different error types
- Remove complexit error test

[ENG-8823]: https://nacelle.atlassian.net/browse/ENG-8823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by NWRichmond — APPROVED** [review]
Makes sense to me! Thanks for this PR, @KrisQ 🤝

**Comment by mdarrik** [comment]
Do we need the `handleGraphQLErrors` logic at all, or [is this throw sufficient](https://github.com/getnacelle/nacelle-js/blob/b278b7a686ee0924ea25eafbe4684f005a7efdc8/packages/storefront-sdk-plugins/commerce-queries/src/utils/handle-errors.ts#L10) since urql already concats the graphql errors into the `error.message` property. 


```ts
throw new Error(error?.message)
```

Error message in this PR: 

```
Error: Error: Storefront GraphQL Error:Cannot query field "edgesx" on type "ContentConnection". Did you mean "edges"? (Error Ref Id: "Root=1-63f6c125-7407c9964a7e61c851b0294a")
```

Raw error.message without the graphql error handling: 

```
Error: [GraphQL] Cannot query field "edgesx" on type "Query".
Trace ID: Root=1-63f6c3cd-4247a9a10a98bdef5fb74744. Please include this Trace ID in support requests.
```

**Comment by KrisQ** [comment]
Thank you for noticing this @mdarrik, I simplified it further for this PR!
Any objections @NWRichmond?

**Review by mdarrik — APPROVED** [review]
Thanks!

**Pull request merged**
